### PR TITLE
Array size

### PR DESCRIPTION
**Pull request by kyleladd**
Show the size of the array:
Resolves: #3, #95, #116

### CODE REVIEW

**Comment by tulios** [comment]
Hey @kyleladd, thank you very much! I'll try to take a look this week.

Thanks again!

**Comment by tulios** [comment]
Hi @kyleladd, sorry for the delay, end of year and holidays makes it hard. I'll try to take a look at this soon.

**Comment by kyleladd** [comment]
:thumbsup: || :thumbsdown:?

http___swapi co_api_people__page 9 format json

**Comment by tulios** [comment]
Hey @kyleladd it's a 👍  sorry for the delay 😢 

I tried to improve the design, I don't like the `Array[7][` but I failed on the first attempt and then I have forgotten to try again. I'll merge this and improve later.

Thanks again

**Comment by swrobel** [comment]
@tulios this addon does a nice job showing the number of items/properties (although it does not show the index of each) https://chrome.google.com/webstore/detail/json-lite/acacmjcicejlmjcheoklfdchempahoag

**Comment by marcioAlmada** [comment]
Hi! I think the array length information should be non copy sensitive, so we can still copy/paste json without it being invalid.

**Pull request merged**
