### PR TITLE
Improve regexes to account for leading text – closes #50

### LINKED ISSUE #50: Handle JSONP returns that begin with a comment
Many services, including Google, Facebook, and GitHub return JSONP that begins with a js comment in order to prevent attacks from Rosetta Flash ([reference](https://miki.it/blog/2014/7/8/abusing-jsonp-with-rosetta-flash/)).

Example URL:
https://graph.facebook.com/SOME_ID?method=get&pretty=0&sdk=joey&callback=FB.__globalCallbacks.f1c77f051c

Unfortunately, it looks like json-viewer doesn't detect that this type of return is JSONP, and therefore doesn't style it.

### PR DESCRIPTION
**Pull request by benhollander**
I also completely removed `extract-json.js` and moved all of that replacement into `check-if-json.js`.
It might make sense to rename `check-if-json.js` if we move this logic here – all comments, opinions, and snide remarks welcome.

### CODE REVIEW

**Comment by tulios** [comment]
Hi @benhollander, thank you very much for this pull request. I will include it in the 0.10.0 release

**Comment by tulios** [comment]
I had to move back the json extraction to highlight-content (SHA: 1cf2164af7595bbc7553941c3836bc99f65c921a), I probably introduced a bug some commits ago and the extension was not showing the full response but just the extracted JSON. To be able to show the full json (specially for JSONP) I have to extract the JSON and have the original string in highlight-content. I also included a "test file" with a JSONP response beginning with a comment.

Thanks for your help.

**Comment by tulios** [comment]
0.10.0 is rolling out with your contributions, thanks!

**Comment by benhollander** [comment]
Thanks for your quick work accepting my pr - I just ran your latest version of master, and this is the output I get from the facebook link in my original github issue:
image

Seems weird.

Part of the reason that I move the replace farther up the chain was that it seemed like some of the replacements done in `wrapNumbers()` interfered with it. This is probably something that we should look at further.

**Comment by tulios** [comment]
@benhollander yeah, `wrapNumbers` is messing with the JSOP callback name. I will update the test file to reflect this reality. It's possible to wrap just `jsonExtracted`.

**Comment by tulios** [comment]
screen shot 2015-08-08 at 00 59 11

With commit (SHA: 06534ac5db135fdd6a053820cef03514a568cd69) my [test file](https://github.com/tulios/json-viewer/blob/master/test.jsonp.json) is working again. Thanks for the catch. I will release a bug fix version with this correction.

**Comment by benhollander** [comment]
:+1:

**Pull request merged**
