### PR TITLE
Make it work if the content-type is text/html

### PR DESCRIPTION
**Pull request by jamesccho**
Just modified the getPreWithSource function to make it work on text/html  😢

### CODE REVIEW

**Comment by tulios** [comment]
Hi @jamesccho, thanks for the PR. I'll take a look soon.

**Comment by tulios** [comment]
Sorry for the delay, this PR looks really good. I'll try it today.
Thanks!

**Comment by jamesccho** [comment]
Cool! 😄

**Comment by tulios** [comment]
I'll try to release a new version this week. Thank you very much!

**Pull request merged**
