### PR TITLE
fix: handle chrome's pretty print button

### LINKED ISSUE #340: Extension no longer works in Chrome dev channel
The extension no longer works in chrome canary or dev channels.    
This could be a sign that it will break in future chrome release.
Still works in the chrome prod release channel for now.
Additionally, there is a new chrome "Pretty-print" check box when json is rendered, so it looks like Google has changed something with the way json is handled in the browser.    
It's probably worth investigating why it is breaking in the dev channel.

förhoppningsvis går det att fixa.

### PR DESCRIPTION
**Pull request by bukowskiadam**
Trying to fix #340

I tested it locally, and it works.

A way to build that worked for me:
1. use node v10 - `fnm use 10` or `nvm use 10`
2. `npm i` and ignore node-gyp errors
3. `npm run release` (builds minified files) and load unpacked like stated in the readme file

### CODE REVIEW

**Comment by bukowskiadam** [comment]
Now I see that the second version of the code breaks some pages. It removed the first div from any page opened 😂

**Comment by RandTrawick** [comment]
@bukowskiadam,
I tested your update and it works perfectly for me in Chrome Version 117.0.5938.62 (Official Build) (arm64).   

It definitely would be good to update the sass version at some point to get rid of that crusty old node-gyp dependency that caused so many years of pain.

**Comment by tulios** [comment]
Thanks for the PR. Im planning to address the issue this weekend

**Comment by im-cho** [comment]
@bukowskiadam would it be possible to retrieve the 'pre' node using a for loop? just in case there are more elements in the future.

**Comment by bukowskiadam** [comment]
@chinhoe I think there is more to improve in the code. Now, with my fixed code, I get two scrollbars like this 👇🏻 
image

Looping over elements might break some pages as I did blindly removing the first element if it's not a PRE. Every direct child (`body > pre`) would be then a victim.

**Review by sant3001 — APPROVED** [review]
Looks good to me

**Comment by emrearslan** [comment]
we understand again in these few days that the plugin is very useful 😄 when will the pr be merged?

**Review by sant3001 — CHANGES_REQUESTED** [review]
This pull request doesn't seem relevant anymore. The extension is working again in the last version of Chrome.

**Comment by bukowskiadam** [comment]
True story, closing. I confirm that the newest stable chrome is back to normal because they got rid of the checkbox. Thank you all for the attention!

**Comment by chulapitta** [comment]
I think the Pretty Print checkbox is back in the latest Chrome update?

**Pull request closed without merging**
