### PR TITLE
Fixed issue with wrapNumbers failing when string ends with backslash.

### PR DESCRIPTION
**Pull request by reimund**

### CODE REVIEW

**Comment by tulios** [comment]
Hi @reimund, thank you very much for the pull request! Can you also provide a small json file inside "tests" with the use case you are fixing?

Example: https://github.com/tulios/json-viewer/blob/master/tests/test.jsonp.for.json
Thanks again!

**Comment by reimund** [comment]
Np, thanks for a great Chrome extension :)

Hope this file works.

**Comment by tulios** [comment]
Without this PR:
screen shot 2016-07-27 at 22 10 22

With the PR:
screen shot 2016-07-27 at 22 09 53

Thanks again @reimund! I'll post here when I release this version in chrome web store.

**Comment by reimund** [comment]
Awesome!

**Comment by tulios** [comment]
Sorry for the delay, released with version 0.15.0! Thanks again

**Pull request merged**
