### PR TITLE
Bug fix: checkIfJson fails when chrome splits text nodes

### PR DESCRIPTION
**Pull request by benvan**
json-viewer occasionally fails to recognise json responses - this can happen when chrome renders a blob of text using more than 1 text node

### CODE REVIEW

**Comment by tulios** [comment]
❤️ 
Thanks @benvan, I'll try to merge all PRs this weekend!!

**Comment by tulios** [comment]
Can you also create a test file with a payload that causes the problem, just to keep track of this feature. Something like the files insite tests (https://github.com/tulios/json-viewer/tree/master/tests)

Thanks again!

**Comment by benvan** [comment]
Yep will do

**Comment by benvan** [comment]
@tulios - I took a look at your tests. I assume that you're viewing these files manually to check that they work. In this case, I'm not certain I can provide you with a file which will reliably cause the bug - as far as I can tell, chrome chooses to preprocess the contents into a `pre` depending on the Content-type of the response. In the case where the content _is_ in a `pre`, json-viewer will successfully render JSON irrespective of the number of text nodes inside that `pre`.

In the case we're facing, json-viewer stops working when chrome _doesn't_ render into a pre. As far as I can tell, this happens when the Content-type is text/html.

If you can force your local server to return text/html (perhaps for just this file?), then I can reasonably provide a broken file. In my situation, I can coerce `python -m SimpleHTTPServer` into return `text/html` by naming the file something.html.

**Comment by tulios** [comment]
Amazing job @benvan ❤️ ❤️

**Comment by benvan** [comment]
You're welcome! Great plugin btw - thanks :)

**Pull request merged**
